### ISSUE TITLE
Support Helpers

### ISSUE THREAD

**Issue by aaronjensen** [jimsynz/hamlbars#1]
This gem seems to be more maintained than https://github.com/thegorgon/hamlbars but it has one advantage, it supports Rails helpers. Obviously the support is imperfect because there is no request while the template is building, but it is very helpful. 

Thoughts?

**Comment by jimsynz** [comment]
I gave some thought to this when I put the gem together. I decided that since most helpers require a request method there was too much possibility for developer confusion. I would think that it would be more appropriate to send a pull request to rails creating a sprockets safe helpers module?
Another option would be to delegate the safe methods to ActionView but it seems like a bad idea to manually curate a list of safe methods. What are your thoughts?

**Comment by aaronjensen** [comment]
agreed, it is dangerous. I'm not sure how a safety net would be put in place. Could we somehow monkey patch request to raise at the appropriate time? I haven't tried it yet, but I wonder what would happen during asset precompilation if you used one of these unsafe helpers.

I'm primarily interested in form helpers and such. Maybe if there was just an easy way to include helpers in an initializer or something?

**Comment by jimsynz** [comment]
Hrm. I wonder if we can simply add a method_missing chain in our Helpers extension that will pass through safe methods, but NoMethod the bad ones?

**Comment by aaronjensen** [comment]
Then we'd be maintaining a list of safe ones. Also, I'd think it'd be better to metaprogram them in rather than method_missing them. Of course, perf isn't a super critical thing in this because it's asset precompiled in production

**Comment by jimsynz** [comment]
Agreed. Not sure the best way to do it, since everyone in the Rails community says doing this is A Very Bad Thing.

**Comment by jimsynz** [comment]
I have added support in the latest commit, see README.md. Can you test and confirm that it works as expected in your use case?

Thanks.

**Comment by aaronjensen** [comment]
The commit in my branch didn't actually seem to work, that's why I never actually issued a pull request. Did you test it/were you able to get it working? I was just trying it and moving machines so I pushed it up to github... it was never intended to make it in. I opened the issue in hopes you'd know a better (working) way. Sorry about the confusion.

**Comment by jimsynz** [comment]
It appears to be working for me in my latest HEAD commit, at least he following template worked when I tried it:

```
= hb 'hello' do
  = number_to_currency 2000  
```

**Comment by aaronjensen** [comment]
Just to confirm, this is working for us as well, thanks!
