### ISSUE TITLE
Template options for ember

### ISSUE THREAD

**Issue by tscolari** [jimsynz/hamlbars#10]
Hello, maybe I'm  missing something, but the template options doesn't seem to work at my project. I created an initializer with:

```
Hamlbars::Template.template_destination    = 'Ember.TEMPLATES'
Hamlbars::Template.template_compiler       = 'Ember.Handlebars.compile'
Hamlbars::Template.template_partial_method = 'Ember.Handlebars.registerPartial'
```

I'm using ember-rails (not emberjs-rails) - https://github.com/emberjs/ember-rails, the output javascript comes like this:

```
Handlebars.templates["ember_templates_sessions_logged_out_box"] = Handlebars.compile...
```

I was expecting something like this:

```
Ember.TEMPLATES["ember/templates/sessions/logged_out_box"] = Handlebars.template...
```

did I miss anything or this is not supposed to work this way?

**Comment by jimsynz** [comment]
Are you using a Gem version or HEAD? Which version?

**Comment by tscolari** [comment]
I'm using the rubygems' version: hamlbars (2012.2.22)

**Comment by jimsynz** [comment]
Hi there.  Can you try the latest gem (2012.3.21) master and change your initializer to:

```
Hamlbars::Templates.render_templates_for :ember
Hamlbars::Templates.enable_precompiler!
```

This should give you the output you are looking for (works for me, at least).

**Comment by tscolari** [comment]
Thank you, the left side is perfect.
I'm don't know much about ember/handlebars, but the right side of the assignment still different, does it matter?

for example, a pure .handlebars file would generate something like this:

```
Ember.TEMPLATES["ember/templates/sessions/logged_in_box"] = Handlebars.template(function anonymous(Handlebars,depth0,helpers,partials,data) {
helpers = helpers || Ember.Handlebars.helpers;
  var buffer = '', stack1, stack2, stack3, stack4, tmp1, self=this, functionType="function", helperMissing=helpers.helperMissing, undef=void 0, escapeExpression=this.escapeExpression;


  data.buffer.push("<div class='user menulist'>\n  <ul>\n    <li class='first'>\n      ");
  stack1 = depth0;
  stack2 = "currentUser.username";
  stack3 = {};
  stack4 = "true";
  stack3['escaped'] = stack4;
  stack4 = helpers._triageMustache || depth0._triageMustache;
  tmp1 = {};
  tmp1.hash = stack3;
  tmp1.contexts = [];
  tmp1.contexts.push(stack1);
  tmp1.data = data;
  if(typeof stack4 === functionType) { stack1 = stack4.call(depth0, stack2, tmp1); }
  else if(stack4=== undef) { stack1 = helperMissing.call(depth0, "_triageMustache", stack2, tmp1); }
  else { stack1 = stack4; }
  data.buffer.push(escapeExpression(stack1) + "\n    </li>\n    <li>\n      <a href=\"/usuarios/logout\" data-method=\"delete\" data-remote=\"true\" rel=\"nofollow\">Sair</a>\n    </li>\n  </ul>\n</div>\n");
  return buffer;
});
```

while the .hamlbars (of a different template) was:

```
Ember.TEMPLATES["ember/templates/sessions/logged_out_box"] = Ember.Handlebars.compile("<div class=\'user menulist\'>\n  <ul>\n    <li class=\'first\'>\n      <a href=\"/usuarios/registrar/sign_up\" class=\"item\">Cadastre-se</a>\n    </li>\n    <li {{bindAttr class=\"controller.isLoginBoxVisible:active controller.isLoginBoxVisible:dropmenu\"}}>\n      <span class=\'droptab\'>\n        <a {{action \"toggleLoginBox\" on=\"click\"}}>\n          <span class=\'item\'>\n            Login\n          </span>\n        </a>\n      </span>\n      <div id=\'login_form_holder\'></div>\n    </li>\n  </ul>\n</div>");
```

Ember.Handlebars.compile vs Handlebars.template

I'm asking because some bindings in my view aren't working as I expected, and I would like to know if this could be the cause or I should look for it in somewhere else.

**Comment by jimsynz** [comment]
It's serving an uncompiled temlpate, meaning that the client is compiling the template. This doesn't really matter in development, but is important in production.  I have added support to compile the output but it needs to use different compilers for Ember vs Handlebars, so I have to do a little more work on that front.

**Comment by ghost** [comment]
+1 on this issue.  Workaround listed above didn't work.

**Comment by petejkim** [comment]
+1

**Comment by LevelbossMike** [comment]
Is this issue already solved? I am seeing the exact same behavior and am not able to solve this with the workaround above. I am using the current version ~> 1.1 from ruby gems

_edit_
I think I have found the reason for my problem. The initializers that setup Hamlbars for usage with Ember are not getting called before asset compilation. I guess the second answer fixes the problem.

http://stackoverflow.com/questions/9235292/how-can-i-run-some-initializers-when-doing-a-rails-assetsprecompile

or simply setting 

``` ruby
config.assets.initialize_on_precompile = true
```

**Comment by jimsynz** [comment]
Closing because compilation has been removed from the v2.0 branch.
