### ISSUE TITLE
Drop .hbs extension support?

### ISSUE THREAD

**Issue by joliss** [jimsynz/hamlbars#11]
[Ember-rails](https://github.com/emberjs/ember-rails) supports the .hbs extension for plain Handlebars templates. It seems reasonable to me to interpret "hbs" as standing for Handlebars, rather than the less common Hamlbars.

How about dropping .hbs support in Hamlbars to avoid ambiguity?

**Comment by jimsynz** [comment]
Makes sense. Changed in 0cc373c6e11588114beb797e5355a6a15433d61f.
