### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by joliss** [jimsynz/hamlbars#12]
I think you'll run into problems if you ever want to switch to [normal version numbers](http://semver.org/), since 2012.3.21 > 1.0, I presume.

To avoid major pains for users when this gem becomes more popular, how about switching now (releasing 0.1 or 1.0) and yanking all 2012.\* versions?

**Comment by jimsynz** [comment]
I think this is pretty difficult since there are already a bunch of people using it. I'd be interested in hearing opinions from some others first.

**Comment by joliss** [comment]
Right, yanked gem versions stop being installable [even when they are listed in Gemfile.lock](https://github.com/rubygems/rubygems.org/issues/296). My thinking was that as hamlbars is only a few months old, it's likely that people aren't using it in bigger production sites yet.

> I'd be interested in hearing opinions from some others first.

Sounds reasonable.

**Comment by botandrose** [comment]
+1

**Comment by jimsynz** [comment]
Okay, so if we were to do it then what's the plan?  There are already ~1800 downloads in the wild (according to rubygems) so perhaps rather than yanking them we should just pick an arbitrarily large version number and start from there?

**Comment by joliss** [comment]
Let's ask @drbrain, he might know. Eric, James is trying to get from version "2012.3.21" to version "1.0.0". The problem is that 2012.3.21 > 1.0.0. Is there a recommended way to do this kind of switch? Simply yanking all the old 2012.x.y versions might cause some disruption.

**Comment by joliss** [comment]
(In other words, he's trying to switch the versioning scheme for his gem from "2012.x.y" to "1.x.y".)

**Comment by drbrain** [comment]
You'll need to yank all the 2012.x.y versions to have 1.x.y be greater.

You could re-upload them as 0.2012.x.y to keep the old versions available, but those links will be gone.

You could also jump to an arbitrary future version like 3000 and start semver from there.

**Comment by jimsynz** [comment]
Thanks Eric. I'd like to do a 1.0 release but I'd like to refactor the tests first and get compilation for handlebars and ember working nicely. Also I'd like to include a gem binary and support for rake pipeline. @joliss I'd really appreciate some pulls if you have time. 

## 

James Harton
sociable.co.nz
@jamesotron
+64226803869

**Comment by joliss** [comment]
Yes, thanks Eric, that's very helpful!

James Harton reply@reply.github.com
wrote:

> I'd like to do a 1.0 release but I'd like to refactor the tests first and get compilation for handlebars and ember working nicely. Also I'd like to include a gem binary and support for rake pipeline.

Maybe push 1.0 and defer those things for 1.1 and 1.2? You could mark
the existing precompile support as alpha/experimental.

> @joliss I'd really appreciate some pulls if you have time.

I'll keep hamlbars in mind for some coding love.

**Comment by jimsynz** [comment]
Thanks for your help @joliss. Closing.

**Comment by joliss** [comment]
@drbrain Just an update on this in case you're interested: Yanking the 2012.x.y versions and pushing 1.0.0 worked for new users, but bundler users wouldn't get upgraded to 1.0.0 when they called `bundle update`, without specifying `~> 1.0`.

Oh well.
