### ISSUE TITLE
undefined method `register_engine' for Sprockets:Module (NoMethodError)

### ISSUE THREAD

**Issue by beghbali** [jimsynz/hamlbars#14]
I'm using:
- coffee-rails (3.1.1)
- ember-rails (0.4.0)
- haml (3.1.4)
- hamlbars (2012.3.21 d820100)
- rails (3.1.3)
- sprockets (2.0.3)

I get this error when starting up server. adding the following line to hamlbars.rb fixes it:
require 'sprockets/engines'

**Comment by jimsynz** [comment]
just to confirm - you are running from Rails, right?

**Comment by beghbali** [comment]
yes. Rails on unicorn.

**Comment by jimsynz** [comment]
I can't see how this can happen, since Sprockets should be required in `config/application.rb`

```
# Pick the frameworks you want:
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "active_resource/railtie"
require "sprockets/railtie"
# require "rails/test_unit/railtie"
```

Can you check it?

Ta.

**Comment by beghbali** [comment]
I have
require 'rails/all'
I tried adding those requires manually but I still get the error when starting up.
Any gems that may conflict with hamlbars?
While I have your attention, How do I use hb in haml attributes?:
%tr.team{:bind => {:id => 'dom_id(team)'}}

**Comment by jimsynz** [comment]
In response to your latter question, the hash argument to a tag is just plain old ruby, so you can just do:

```
%tr.team{:bind => { :id => dom_id(team) }} 
```

or even:

```
%tr.team{ bind: { id: dom_id(team) }}
```

**Comment by beghbali** [comment]
James, my latter question was about how I can use js/coffee script in the tags. I am using hamlbar templates with Ember.js and I need to set some attributes based on the Ember object being rendered. My understanding was that the request for the hamlbar doesn't come to server in Ember and is precompiled in the js loaded on the client. Is there a way to set attributes based on handlebars so in the eventual rendering it is substituted by the js object attributes?

**Comment by jimsynz** [comment]
I'm not quite sure that I understand your question, but take a look at http://hamlbars-demo.herokuapp.com/ and see if it gives you some pointers.

**Comment by jimsynz** [comment]
@beghbali any updates on this issue or should I close it?  Thanks.

**Comment by beghbali** [comment]
Go ahead and close it. I am not running into in in latest projects.

On Tue, Jun 26, 2012 at 11:11 PM, James Harton <
reply@reply.github.com

> wrote:
> 
> @beghbali any updates on this issue or should I close it?  Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jamesotron/hamlbars/issues/14#issuecomment-6595569

## 

Bashir Eghbali

bashireghbali.com
linkedin http://www.linkedin.com/in/bashireghbali

**Comment by jimsynz** [comment]
Thanks.
