### ISSUE TITLE
Support #if - else statements?

### ISSUE THREAD

**Issue by botandrose** [jimsynz/hamlbars#15]
currently,

```
= hb "if condition" do
  %h1 ZOMG
= hb "else" do
  %p oh no
```

compiles to

```
{{#if condition}}
  <h1>ZOMG</h1>
{{/if}}
{{#else}}
  <p>oh no</p>
{{/else}}
```

I didn't see anything in the README or specs for handling this.

**Comment by jimsynz** [comment]
Hi.

Yeah, it's a bit nasty, but you do it this way:

```
= hb 'if someCondition' do
  <h1>ZOMG, awesomesauce!</h1>
  = hb 'else'
  <h1>sucksauce</h1>
```

Note the indenting of else.  Makes it a bit hard to spot visually, but it's there because `{{else}}` is a helper function which only makes sense within the context of an `#if` or `#unless` block helper.

**Comment by botandrose** [comment]
Thanks, this does indeed work! That implementation makes sense, if not ideal syntax. I suppose the ideal long-term goal  would be to modify haml itself so that the hb helper is unnecessary, and the standard haml - if / - else just compiles into mustache like one would naively expect.

**Comment by jimsynz** [comment]
I'm not sure that's possible because we don't know at compile time what helpers are defined in your environment. Ember and Handlebars define different implementations of some helpers and some are missing from the other, etc - not to mention any you register for yourself. I think the HB helper will be sticking around for a while.

**Comment by botandrose** [comment]
Ah, I see. I think we have different use-cases. I'm looking for something that's essentially an alternate haml syntax to handlebars, where this project is haml helpers for generating handlebars tags.

I'll try forking elia/haml2erb and see how close that gets me.

**Comment by jimsynz** [comment]
good luck! Keep us informed if you come up with something.

**Comment by botandrose** [comment]
Thanks! Just pushed out 0.0.1 of haml2handlebars : https://github.com/botandrose/haml2handlebars . It appears to work, and the tests pass, but I haven't tried it in a Rails app yet! Starting a new gem to integrate it into the asset pipeline. I suppose I'll subclass Tilt::Template like you did? You know, come to think of it, I'll just try forking this and replacing the guts wiith haml2handlebars.

**Comment by jimsynz** [comment]
For people who find this via google, take a look at https://gist.github.com/2992040 if you're having issues.

**Comment by machty** [comment]
this isn't PR-ready (needs test cases), but here's a fork that allows for the following syntax for anyone who's interested:
      # = hb 'if someprop' do
      #   %p it was true
      # = hb 'else' do
      #   %p it was false

https://github.com/machty/hamlbars
