### ISSUE TITLE
Moving javascripts to vendor/assets/javascripts?

### ISSUE THREAD

**Issue by tscolari** [jimsynz/hamlbars#16]
Hello,
I'm trying to use this gem with backbone, and it would be useful for me if the javascripts could be into the assets folder, so I can link them in my manifest. 

If this is not a problem internally, I would love ithis :)

**Comment by jimsynz** [comment]
You mean the ember and handlebars ones? I think you're better off using ember-rails and handlebars-rails which will vendor the assets correctly and keep in sync with the upstream versions.  I will only be upgrading the runtime versions included with hamlbars when there is a breaking change with the way templates are compiled.

**Comment by jimsynz** [comment]
See #24.
