### ISSUE TITLE
Handlebars.templates missing in ember.js master branch?

### ISSUE THREAD

**Issue by awt** [jimsynz/hamlbars#25]
I've been going through the process of upgrading to ember.js master branch, and it appears that Handlebars.templates no longer exists, which causes an error when hamlbars attempts to set Handlebars.templates["path/to/template"].  

It could very well be that something else in my code is busted, but I wanted to ask if you could point me anywhere to make sure that the handlebars library still supports setting paths via Handlebars.templates?

**Comment by jimsynz** [comment]
Have you tried adding

``` ruby
Hamlbars::Template.render_templates_for :ember
```

to an initializer?

**Comment by awt** [comment]
Gah!  I was not using that.  Up to now I'd been using emberjs-rails, and just switched to ember-rails to be able to use the latest version of ember ( to get access to routing capabilities ).

I am now.  I've verified that the snippet you pasted is being called in the initializer I added, but I'm still seeing this:

Handlebars.templates["requester/views/browse"] = Handlebars.compile{etc.........}

**Comment by jimsynz** [comment]
What gem version are you using?

**Comment by awt** [comment]
I'm using 1.0.  I tried actually removing the hamlbars gem from my Gemfile, restarting rails and clearing my browser cache and the Handlebars.templates... lines were still at the bottom of my app.js file.  Something very strange is going on with my setup.

**Comment by jimsynz** [comment]
Try nuking the contents of tmp/cache/ and public/assets/ 

## 

James Harton
sociable.co.nz
@jamesotron
+64226803869

**Comment by awt** [comment]
Bingo!  Thanks a lot.  I totally forgot about those two caches.

**Comment by jimsynz** [comment]
Great, so this issue can be closed?

**Comment by awt** [comment]
Closing.
