### ISSUE TITLE
New {{action}} syntax in Ember

### ISSUE THREAD

**Issue by joliss** [jimsynz/hamlbars#29]
The syntax of the {{action}} helper was recently changed ([83b7a61a](https://github.com/emberjs/ember.js/commit/83b7a61a892e55423cf1e66f606b13435bcab8f0)), so Hamlbars doesn't work with Ember master anymore.

Should we just update it to use the `context` option as the first argument to {{action}}?

I'm honestly a bit unhappy with the verbosity of our current syntax, so I wonder if we should improve it along with this change.

Right now we have

```
event: {action: 'edit', context: 'model'}
```

to yield

```
{{action edit context="model"}} // old
{{action edit model}} // new
```

How about this instead?

```
action: 'edit model'
```

So there's no surrounding `event`. We lose the ability to have multiple actions, but at least in Ember, this [isn't supported anyway](http://stackoverflow.com/questions/11544565/ember-handling-multiple-events-with-action-tag) to my understanding.

Options could be inline, like so:

```
action: 'edit model href=true'
```

**Comment by joliss** [comment]
I'm volunteering a PR btw. Let me know what you think.

**Comment by jimsynz** [comment]
That sounds great. It's pretty easy to support both the old and proposed syntaxes by just testing for hashiness. Go for it :)

**Comment by artzte** [comment]
There is an unfortunate collision with form action attributes with this. How about calling it ember-action or just use the old event keyword with a plain string with the new syntax?
