### ISSUE TITLE
Precompilation?

### ISSUE THREAD

**Issue by aaronjensen** [jimsynz/hamlbars#3]
It'd be great to borrow precompilation from https://github.com/leshill/handlebars_assets

**Comment by jimsynz** [comment]
I was looking at the code in https://github.com/emberjs/ember-rails to add to both emberjs-rails and hamlbars, I'll take a look at handlebars_assets.

**Comment by jimsynz** [comment]
I've been looking at this, but I need to fix the mixin alias method garbage first. :)

**Comment by beghbali** [comment]
How are you guys handling heroku deployments with initialize_on_precompile=false. I can't get the hamlbar/ember templates to compile it seems.

**Comment by jimsynz** [comment]
Closing because compilation has been removed from the v2.0 branch.
