### ISSUE TITLE
Uncompiled code is returned using Ember templates

### ISSUE THREAD

**Issue by michaelbaudino** [jimsynz/hamlbars#34]
Hello,

I'm trying to use Hamlbars in a Ember/Rails project to write my Handlebars templates in HAML, but I can't figure out how to make it work (see below for version numbers).

I've installed Hamlbars using Bundler (gem is hamlbars 1.1.0), then added `Hamlbars::Template.render_templates_for :ember` to an initializer, but the HAML code does not seem to be compiled.

Here is my `app/assets/javascripts/templates/toto.handlebars.hamlbars` :

``` haml
#mycontainer
  %h1 Toto
```

And this template (called by a Ember.View) displays :

``` html
Ember.TEMPLATES["templates/choose_resort"] = Ember.Handlebars.compile("
\n
Toto
\n
"); 
```

(this appears uncompiled on my webpage, and even if it has been compiled, there's no `div` nor `h1` markup)

Here is what I would have expected instead :

``` html
<div id="mycontainer">
  <h1>Toto</h1>
</div>
```

Anyway, could you please tell me if newer Ember.js are not working with Hamlbars, or if I'm missing something here ? Did I mis-named the template file ? Did I forgot to manually call some compiler ? Or am I just trying to do something that is not supposed to be done ?

Thanks a lot in advance.
##### Versions
- Rails is 3.2.2
- Ember is 1.0.pre-90-g60e3c05 (ember-latest at the time of writing)
- Handlebars is 1.0.rc.1 from ember-rails 0.7.0 gem

**Comment by thepixelmonk** [comment]
I am getting this as well.

**Comment by jimsynz** [comment]
Closing because asset compilation is being removed as of 2.0. You can use ember-rails to compile your templates by naming them "my_template.js.hbs.hamlbars"
