### ISSUE TITLE
Doesn't work with latest handlebars

### ISSUE THREAD

**Issue by jshou** [jimsynz/hamlbars#36]
The latest handlebars doesn't define a Handlebars.templates object, which causes hamlbars to fail.

**Comment by jimsynz** [comment]
Hi @jshou. Can you try using the v2.0 branch in conjunction with handlebars_assets? The v2.0 branch completely removes all the compilation code from hamlbars, and just outputs a rendered handlebars template for the upstream gem to process.

**Comment by jshou** [comment]
Hi @jamesotron, I added handlebars_assets to the assets group in my Gemfile, and set my Gemfile to use hamlbars with branch v2.0. My template still looks like this, though:

```
Handlebars.templates["app/views/addproduct"] = Handlebars.compile("...
```

It throws an exception because Handlebars.templates is undefined.

**Comment by thepixelmonk** [comment]
Getting this as well =/.

**Comment by jshou** [comment]
any update on this?

**Comment by jimsynz** [comment]
I'd suggest checking the documentation on [handlebars_assets](https://github.com/leshill/handlebars_assets), since with the v2.0 branch hamlbars isn't doing any compilation.
