### ISSUE TITLE
context doesn't get passed in an ember action

### ISSUE THREAD

**Issue by mehulkar** [jimsynz/hamlbars#37]
``` handlebars
<a {{action someAction context="object" target="controller"}}>Click Me </a>
```

``` haml
%a{:_action => 'someAction context="object" target="controller"'}Click Me
```

target gets specified fine, but the context object doesn't get passed through :(

**Comment by joliss** [comment]
The Ember syntax got changed. Now you just pass the context like an argument:

```
:_action => 'someAction object target="controller"'
```

For future reference, this would really be an Ember question. Hamlbars just passes the string through. #emberjs on Freenode or Stackoverflow tend to be good places to ask these kinds of questions.
