### ISSUE TITLE
Nested conditionals not supported

### ISSUE THREAD

**Issue by Breefield** [jimsynz/hamlbars#41]
```
{{#if author}}
  {{location.address}}
{{else}}
  {{location.approx_area}}
{{/if}}
```

This parses as haml prior to handlebars.runtime, so the nesting breaks haml.
One can wrap this in :plain, or not nest conditionals. Neither are ideal.

**Comment by jimsynz** [comment]
Are you using the hamlbars helper?

``` haml
= hb 'if author' do
  = hb 'location.address'
  = hb 'else'
  = hb 'location.approx_area'
```

**Comment by jimsynz** [comment]
Closing since there has been no response.

**Comment by Breefield** [comment]
Hey James, sorry for not getting back sooner—that works for me :+1:

**Comment by rpocklin** [comment]
Any reason we have to use the `hb` helper?  I find the {{}} syntax easier to read and type, but it seems there's bug(s) with parsing nested `{{handlebars}}` statements eg. if conditions and the like.

**Comment by jimsynz** [comment]
The main reason is that HTML just sees `{{}}` as text, and won't let you nest text within other text. For example, the following will raise an exception:

``` handlebars
{{#each post in controller}}
  {{post.title}}
{{/each}}
```

Whereas this won't:

``` haml
=hb 'each post in controller' do
  =hb 'post.title'
```
