### ISSUE TITLE
Illegal nesting: nesting within plain text is illegal. 

### ISSUE THREAD

**Issue by mrbrdo** [jimsynz/hamlbars#42]
Any idea why? I can't get .haml or .hamlbars assets in my javascripts to work, they seem to be rendering the application layout for some reason...

I get this exception when the application.js is included:

```
<%= javascript_include_tag "application" %>
```

I'm using hamlbars with handlebars_assets to use in javascript (backbone). I'm using Rails 3.2.11 and Haml 3.1.7, Hamlbars 2.0.0

**Comment by jimsynz** [comment]
Can you paste an example of your templates?

**Comment by mrbrdo** [comment]
Regardless. Same error no matter if it's totally blank, has like %h3 something or whatever.
Might have to do with haml and rails version, not sure. It works fine with haml-coffee so I don't think there's a big problem on my end.

**Comment by jimsynz** [comment]
Your templates are named like `sometemplate.js.hbs.hamlbars` ?

**Comment by mrbrdo** [comment]
yep, just like it said in the docs

**Comment by jimsynz** [comment]
The illegal nesting error is usually because people are putting actual handlebars tags in the markup, which doesn't work.  Try creating a file called `demoTemplate.js.hbs.hamlbars` inside your assets/javascripts path.

``` haml
%h3 Demo
= hb 'demoText'
```

Then request `/assets/demoTemplate.js`

**Comment by mrbrdo** [comment]
Well like I said I get the error even if the file is empty. The error occurs in javascript_include_tag "application", so I don't need to even request the file itself. I had it under assets/javascripts/templates
I can't check right now, will have to get back to you
But I'm pretty sure that's not the problem

**Comment by jimsynz** [comment]
Right, I get that. I want to know if it's a problem with rendering the asset at all, or with including it in the manifest.

**Comment by mrbrdo** [comment]
I'm pretty sure the problem occurs when it's included, because my page errors out completely, not only the request for the asset.

**Comment by jboshers** [comment]
I'm having the exact same problem. 

Following the Demo config above I get the following:

throw Error("Haml::SyntaxError: Illegal nesting: nesting within plain text is illegal.\n  (in /Users/Desktop/hamltest/app/assets/javascripts/demo.js.hbs.hamlbars)")

**Comment by jboshers** [comment]
I got it working by using changing the template name to demo.js.hamlbars

I'm also using handlebars_assets FWIW.

**Comment by gvt** [comment]
+1 this worked for me too.

**Comment by maxwellE** [comment]
Changing to example.js.hamlbars also worked for me.

**Comment by errakeshpd** [comment]
i also faced the same issue with the haml, 
Haml::SyntaxError in Notifications#index
Showing /home/pd/proj/ruby/arividam/app/views/notifications/index.html.haml where line #3 raised:
Illegal nesting: nesting within plain text is illegal.

<% @notifications.each do |notification| %>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title"><%=  notification.title  %></h3>
      <span class="pull-right clickable"><i class="glyphicon glyphicon-minus"></i></span>
  </div>
  <div class="panel-body">
      <%= notification.description %>
      <%= notification.author %>
      <%= link_to 'Show', notification %>
      <%= link_to 'Edit', edit_notification_path(notification) %>
      <%= link_to 'Destroy', notification, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
</div>

  </div>
  <% end %>
