### ISSUE TITLE
Upgrade to Compile Using Handlebars 1.0.0

### ISSUE THREAD

**Issue by ksylvest** [jimsynz/hamlbars#46]
When integrating with the latest `handlebars_assets` the following error occurs:

> Uncaught Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 1.0.0) or downgrade your runtime to an older version (== 1.0.0-rc.3).

**Comment by jimsynz** [comment]
Hi @ksylvest.  hamlbars doesn't have a dependency on any given version of handlebars. I see that it has legacy versions of the javascripts lying around, which I'll remove, but you should look at updating the handlebars-source gem.

**Comment by ksylvest** [comment]
@jamesotron Sorry about that. Updating the source fixed it.

**Comment by jimsynz** [comment]
No problem. Glad I could help.
