### ISSUE TITLE
Include too old handlebars.js

### ISSUE THREAD

**Issue by tricknotes** [jimsynz/hamlbars#48]
hamlbars 2.0.0 includes `vendor/javascripts/handlebars.js`.

``` js
Handlebars.VERSION; //=> "1.0.beta.5"
```

This file causes the problem that this path is resolved before the another one defined by handlebars-source in my project.

Could you bump next version?

**Comment by jimsynz** [comment]
All done. Just depend on `~> 2.0.1` and you'll be set.

**Comment by tricknotes** [comment]
It works perfectly!!
Great thanks :dizzy:

**Comment by jimsynz** [comment]
My pleasure :)
