### ISSUE TITLE
Block content seems escaped

### ISSUE THREAD

**Issue by inkstak** [jimsynz/hamlbars#5]
Hi,

I've upgraded to the latest version of Hamlbars and the hb blocks are now escaped.

I've seen you made a spec for that - 70f7e8bb3f8bfaa2f8db916c7c861e061aea5d60 - however It doesn't work on my rails app : 

```
%script{ type: 'text/x-handlebars' }
  = hb 'if a_thing_is_true' do
    = hb 'hello'
    %a{:bind => {:href => 'aController'}}
```

returns me :

```
<script type="text/x-handlebars">
    {{#if a_thing_is_true}}{{hello}}
    &lt;a {{bindAttr href=&quot;aController&quot;}}&gt;&lt;/a&gt;{{/if}}
  </script>
```

I'll try to dive into that problem, and keep you inform..

**Comment by inkstak** [comment]
The problem is around the Rails XSS safety, not the output itself.

I found a first approach : https://github.com/blakink/hamlbars/commit/005072236494ea9681b72babd310d2244de82e6c
But I guess it can be improved..

**Comment by jimsynz** [comment]
Thanks for the patch.

**Comment by inkstak** [comment]
You're welcome. Thanks for the gem :)
