### ISSUE TITLE
Can't get hamlbars to play nicely with handlebars_assets

### ISSUE THREAD

**Issue by timherby** [jimsynz/hamlbars#51]
I'm trying to use [hamlbars](https://github.com/jamesotron/hamlbars) with [handlebars_assets](https://github.com/leshill/handlebars_assets), but so far have failed to get them to integrate properly.

Out of the box, I tried including both gems:

```
  gem 'handlebars_assets'
  gem 'hamlbars'
```

And when I create a file with a .hamlbars file, it gets compiled properly, but by the handlebars_assets Tilt template, not the hamlbars Template class.

If I change the extension to "file.js.hbs.hamlbars" (as described here https://github.com/jamesotron/hamlbars#chaining-compilation-using-the-rails-asset-pipeline), I get "file.js.haml.js" as my include, and "file.js" cannot even be downloaded directly.

I then decided to pull the latest version of handlebars_assets which changes the initialization order so that the hamlbars template gets used.  I did this by changing my gemfile to point to the latest commit in this branch: https://github.com/leshill/handlebars_assets/tree/fix-sprockets-register
as described in issue https://github.com/leshill/handlebars_assets/pull/73

```
  gem 'handlebars_assets', git: 'https://github.com/leshill/handlebars_assets.git', ref: '510fb66d96b881e08af67867d6773cf7a1a17ba2'
  gem 'hamlbars'
```

But that doesn't do the trick.  If I keep the filename as "file.hamlbars" no files are included by 

If I switch to "file.js.hbs.hamlbars", I run into this issue https://github.com/jamesotron/hamlbars/issues/42 (Illegal nesting: nesting within plain text is illegal).  If I follow the advice in that thread, and switch "file.js.hbs.hamlbars" to ".js.hamlbars" but then the handlebars template gets returned uncompiled to the browser.

If anyone has any tips about how to use both gems together, I would really appreciate it.  I have cross-posted this to the other gem's forum too (https://github.com/leshill/handlebars_assets/issues/85) for tracking.

**Comment by jimsynz** [comment]
I've commented over on https://github.com/leshill/handlebars_assets/issues/85 about this. Happy to help any way I can, but with handlebars assets stoping over the `.hamlbars` extension, I don't think there's much that can be done.

**Comment by AlexRiedler** [comment]
I was looking to fix this in leshill/handlebars_assets so the extensions are not so definite.

This week a relatively big change to the gem should occur (and hopefully a fix for this will be included; probably by allowing configuration to which extensions are registered by the handlebars_assets gem).

**Comment by timherby** [comment]
Hi Alex & James,  thanks for the quick replies.  

James, it's great to hear that you'll be removing the default registration for hamlbars.  Even if I remove that line locally, though, it looks like there's the issue with a file name "file.js.hbs.hamlbars" being processed as a haml file (causing issue #42) because "TemplatePath.is_haml?" returns true when looking at the full original extension, rather than the remaining extension given the current spot in the asset pipeline.  So it would be great if that could be fixed as well so that both products integrate smoothly.

Thanks,

Tim

**Comment by AlexRiedler** [comment]
@timherby, so the issue was that there is a race in who handles the '.hamlbars' extension.

Both the gem 'jamesotron/hamlbars' and 'leshill/handlebars_assets' register for the '.hamlbars' extension; as a result whoever was registered last takes priority in compilation. The leshill/handlebars_assets '.hamlbars' extensions just passes through haml, then through handlebars compilation. (which was the error you were seeing); if you use the experiemental branch (indicated on https://github.com/leshill/handlebars_assets/issues/85) It may solve your issue until it is merged to master in the coming week.

**Comment by timherby** [comment]
Thanks @AlexRiedler.  That does the trick.  Looking forward to the release
