### ISSUE TITLE
How to represent @index variable in the handlebars each loop.

### ISSUE THREAD

**Issue by shishirmk** [jimsynz/hamlbars#60]
I am planning to use the "@index" used in the first answer to the question in this page http://stackoverflow.com/questions/11884960/how-to-get-index-in-handlebars-each-helper

I get the unexpected token error. So how do i represent that?

**Comment by jimsynz** [comment]
have you tried `=hb '@index'` ?

**Comment by shishirmk** [comment]
Yes i have tried it. I got an error **Uncaught SyntaxError: Unexpected token ,**
Some people have reported this error in the stackoverflow answer comments.

**Comment by jimsynz** [comment]
This is a problem with handlebars.js not hamlbars:

Using the following hamlbars:

``` haml
= hb 'each widget' do
  =hb '@index'
```

generates:

``` handlebars
{{#each widget}}{{@index}}{{/each}}
```

I suggest you raise an issue on barber or handlebars.

Cheers.

**Comment by shishirmk** [comment]
@jamesotron Thanks for taking a look at it
