### ISSUE TITLE
Possible to have empty link-to helper?

### ISSUE THREAD

**Issue by traviswsims** [jimsynz/hamlbars#63]
Hello all,

Is it possible to have an empty Handlebars link-to helper?  Right now, I've got this:

```
=hb 'link-to "someResource.index" class="navbar-brand"' do
  \
```

Is there a better way to get an empty anchor tag without escaping the empty line?  I'm doing this to add a CSS background image instead of text.  Thanks so much.

**Comment by jimsynz** [comment]
not really, because the only way that Hamlbars knows you want to generate a handlebars block (`{{#link-to}} ... {{/link-to}}`) instead of expression (`{{link-to ... }}`) is that a block is passed.  You could try something like:

``` haml
=hb 'link-to "someResource.index" class="navbar-brand"' {}
```

**Comment by traviswsims** [comment]
Thanks for your quick response and explanation.  I tried `=hb 'link-to ...' {}` and `=hb 'link-to ...' do end`, but got compilation errors.

This isn't a huge deal to me, I just wanted to make sure there wasn't some syntactic sugar I had missed.  Thanks again.
